### ISSUE TITLE
Rich Sharing on FB

### ISSUE THREAD

**Issue by stcalica** [stcalica/stcalica.github.io#16]
Add meta og tags to website for better Facebook Previews

https://developers.facebook.com/docs/sharing/webmasters#markup
1. Read the above post
2. Research meta tags 
3. Add meta tags to our current post using the content.json in the home directory of the code

Ask if need help

**Comment by stcalica** [comment]
http://www.michaelbromley.co.uk/blog/171/enable-rich-social-sharing-in-your-angularjs-app

shit i was too naive. some problems with this and i guess its called "rich sharing"

**Comment by psmith586** [comment]
could cloud it but would need adds to off set the cost if we want to profit

**Comment by stcalica** [comment]
cost isn't too bad. its cheap as hell to have a server instance in the cloud as a VPS. 

the trouble is now having to take care of a server instance instead of having github do it for us haha.

**Comment by stcalica** [comment]
http://fluff.link


solved by creating another web app lol. something to advertise by us haha
