### ISSUE TITLE
Article: Background (maybe)

### ISSUE THREAD

**Issue by psmith586** [stcalica/stcalica.github.io#39]
https://docs.google.com/document/d/1IqSo_JwnvTuMXUDDesMF3O9KnPhsTWCKoSRH15dv_cM/edit

Article about how i got into programming. Ivette urged me to post it to the site but look over and tell me what you think. (Personally thought it was pretty corny)

**Comment by stcalica** [comment]
This is perfect. 
It represents exactly what CodeIsDead should be. 
Breaking of programmer stereotypes, trying to get people to experiment, and first experiences with coding.
Corny and all that actually works in this world. Corny is usually when things are a little close to home and are true. If it didn't work you wouldnt be seeing all the corny shit that there is posted. 
Like I said with the posts and shameless ads if I doesn't work then why do I see tons of people making money by doing it.

**Comment by stcalica** [comment]
Just need some pics possibly or whatever. then it'd be good to go.

**Comment by stcalica** [comment]
better create some backlinks with this one.
